= openCypher Contributor Agreement (oCCA)

[IMPORTANT]
====
https://s3.amazonaws.com/artifacts.opencypher.org/openCypher+Contributor+Agreement.pdf[Download PDF version] You will need to attach the PDF version to your email when you confirm that you are agreeing to this agreement, as described below.
====

These terms apply to your contribution of materials to any project (‘openCypher project’) related to the development and advancement of the Cypher® database query language and hosted at one of the following internet sites (which are managed by Neo4j Inc. as a service to the openCypher community):

A. the *Github organization named ‘openCypher’* and accessible at the internet address https://github.com/opencypher, including but not limited to the following project repositories

 * *openCypher Specification*, being the Grammar definitions and associated tooling, Technology Compatibility Kit, Cypher Improvement Requests, Cypher Improvement Proposals, natural language and formal semantic Specification documents and other documents, diagrams or software that are intended to assist in the implementation of the Cypher language, and are stored or linked to from the openCypher Github repositories named ‘openCypher’ and ‘cypher-language-specification’;
 * *openCypher website*, being all materials relating to the opencypher.org website which are stored or linked to from the openCypher Github repository named ‘website’;
 * *Cypher for Apache Spark*, being software and associated documentation implementing the Cypher language for use in the Spark and other environments, and contained in the openCypher Github repository named ‘cypher-for-apache-spark’, or any successor projects replacing or deriving from that project; and
 * *Cypher for Gremlin*, being software and associated documentation implementing the Cypher language for use in conjunction with artefacts produced by the Apache Software Foundation’s Tinkerpop project and other environments, contained in the openCypher Github repository named ‘cypher-for-gremlin’, or any successor projects replacing or deriving from that project.

B. the opencypher.org website, including presentations and documents discussed at meetings of openCypher implementers and designers which you have agreed to make available to the public on the openCypher website.

C. Cypher Frontend, being software for Cypher query parsing and analysis, contained in the Neo4j Github repository named ‘neo4j’ in the project ‘neo4j’ under the package named ‘org.neo4j.cypher.internal.frontend’.

These terms set out the intellectual property rights you grant to 'us' (Neo4j Inc.) in the contributed materials. If this contribution is on behalf of a company or other organization, the term 'you' will also mean the organization which you identify below. If you agree to be bound by these terms, please confirm your agreement by e-mail to occa@opencypher.org. Include your full name, e-mail address and attach a copy of this agreement.

1. The term 'contribution' means any source code, object code, patch, tool, sample, graphic, specification, manual, documentation, or any other material posted or submitted by you to a project.

2. With respect to any worldwide copyrights, or copyright applications and registrations, in your contribution:

 * you hereby assign to us joint ownership, and to the extent that such assignment is or becomes invalid, ineffective or unenforceable, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free, unrestricted license to exercise all rights under those copyrights. This includes, at our option, the right to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements;
 * you agree that each of us can do all things in relation to your contribution as if each of us were the sole owners, and if one of us makes a derivative work of your contribution, the one who makes the derivative work (or has it made) will be the sole owner of that derivative work;
 * you agree that you will not assert any moral rights in your contribution against us, our licensees or transferees;
 * you agree that we may register a copyright in your contribution and exercise all ownership rights associated with it, including enforcing the copyrights against alleged infringers on your behalf and our own behalf; and
 * you agree that neither of us has any duty to consult with, obtain the consent of, pay or render an accounting to the other for any use or distribution of your contribution.

3. With respect to any patents you own, or that you can license without payment to any third party, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free license to:

 * make, have made, use, sell, offer to sell, import, and otherwise transfer your contribution in whole or in part, alone or in combination with or included in any product, work or materials arising out of the project to which your contribution was submitted, and
 * at our option, to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements.

4. Except as set out above, you keep all right, title, and interest in your contribution. The rights that you grant to us under these terms are effective on the date you first submitted a contribution to us, even if your submission took place before the date you sign these terms.

5. With respect to your contribution, you represent that:

 * it is an original work and that you can legally grant the rights set out in these terms;
 * it does not to the best of your knowledge violate any third party's copyrights, trademarks, patents, or other intellectual property rights; and
 * you are authorized to enter into this agreement on behalf of your organization (if identified below).

6. We will make your contribution available under an Apache 2.0 license, and we may make it available under an additional permissive licence approved by the OSI (Open Source Initiative). Contributions of materials to openCypher projects made by employees or agents of Neo4j Inc and its subsidiaries will be made available under the same license or licenses.

7. These terms will be governed by the laws of the State of California and applicable U.S. Federal law. Any choice of law rules will not apply.

Organization upon whose behalf you are entering into this agreement, if any:

Name

Address

13 March 2018