= TCK Index

The TCK is split into categories based on language constructs.
The two main groups are clauses and expressions.
Each group enumerates its members.
Within each member, there is additional categories.

There is also `wip` directory containing uncategorised features.

== Clauses

Each clause has its own directory of Gherkin `.feature` files, or _feature_ for short.
Each feature follows a naming convention of `<clause-name><group-id>.feature`.


=== CREATE

* `Create1`: Creating nodes
** This group is about the creation of nodes.
* `Create2`: Creating relationships
** This group is about the creation of relationships.
* `Create3`: Interoperation with other clauses
** This group is about how the `CREATE` clause behaves when combined with other clauses.
* `Create4`: Large Create Query
** This group is about queries with a larger number of `CREATE` statements (more than 50)
* `Create5`: Multiple hops create patterns
** This group is about queries with a create pattern that features more than one relationship.
* `Create6`: Negative tests
** This group is about failure cases for the `CREATE` clause; invalid queries.


=== MATCH

* `Match1`: Zero-length patterns
** This group contains `MATCH` clauses without relationships

=== UNION

* `Union1`: Basic morphology and de-duplication semantics
** This group tests that the basic structure holds with respect to projection and de-duplication semantics
* `Union2`: Projection correctness
** This group tests that the more complex aspects of projecting values is correct

=== UNWIND


== Expressions

The expressions are grouped into categories based on their domain.
Each category consists of a number of features.

=== Aggregation

* `Aggregation1`: ...

=== Function

* `Function1`: Type conversion functions
* `Function2`: Negative tests for functions (invalid arguments etc)


=== Literal