= TCK Index

The TCK is split into categories based on language constructs.
The two main groups are clauses and expressions.
Each group enumerates its members.
Within each member, there are additional categories.

There is also an `uncategorized` directory containing uncategorized features.

== Clauses

Each clause has its own directory of Gherkin `.feature` files, or _features_ for short.
Each feature follows a naming convention of `<clause-name><group-id>.feature`.

=== CREATE

* `Create1`: Creating nodes
** This group is about the creation of nodes.
* `Create2`: Creating relationships
** This group is about the creation of relationships.
* `Create3`: Interoperation with other clauses
** This group is about the interplay of the `CREATE` clause with other clauses.
* `Create4`: Large Create Query
** This group is about scenarios with that create a larger number of nodes and relationships.
* `Create5`: Multiple hops create patterns
** This group is about create patterns larger than a single node or a single relationship.
* `Create6`: Negative tests
** This group is about failure cases for the `CREATE` clause; invalid queries.


=== MATCH

* `Match1`: ...

=== UNWIND

* `Unwind1`: ...

== Expressions

The expressions are grouped into categories based on their domain.
Each category consists of a number of features.

=== Aggregations

* `Aggregation1`: ...

=== Functions

* `Function1`: Type conversion functions
* `Function2`: Negative tests for functions (invalid arguments etc)

=== Literals

* `Literal1`: ...
