:numbered:
:toc:
:toc-placement: macro

= CIP2015-10-12 - CREATE

*Authors:* Pontus Melke pontus.melke@neotechnology.com, Mats Rydberg mats@neotechnology.com

toc::[]

== Abstract
This proposal formalizes `CREATE` which is used in Cypher to create nodes and
relationships.

== Motivation & Background
`CREATE` is how nodes and relationships are created in Cypher. The syntax has been around since the very beginning of Cypher but never properly
formalized. With 3.0 on the horizon we want to make sure `CREATE` fits with the
rest of the language, and make sure it is future proof.

== Proposal

`CREATE` will in a lot of aspects work as it does in the current implementation
but this proposal makes `CREATE` closer in syntax to how `MATCH` works.

=== Examples

*_Example:_* +
_Create a single node._

[source, cypher]
----
CREATE ()
----

_Create a node and set two labels and one property on it._

[source, cypher]
----
CREATE (:Person:Administrator { email: 'mats@neotechnology.com' })
----

_Create a relationship of type `KNOWS` between all `:Person` nodes._

[source, cypher]
----
MATCH (a:Person), (b:Person)
CREATE (a)-[:KNOWS]->(b)
----

_Create two nodes and one relationship between them._

[source, cypher]
----
CREATE (me:Source), (you:Destination), (you)<-[:LOVES]-(me)
----

_Create multiple nodes with properties from a parameter list of maps._

[source, cypher]
----
UNWIND { mapList } AS map
CREATE (n:Node)
SET n = map
----

=== Syntax
[source, ebnf]
----
create       = "CREATE", {pattern}, [{",", pattern}]
pattern      = node-pattern | rel-pattern;
node-pattern = "(", [identifier], [{label}], [property], ")"
rel-pattern  = "(", identifier, ")", in-rel | out-rel, "(", identifier, ")"
out-rel      = "-[", [identifier], type, [property], "]->"
in-rel       = "<-[", [identifier], type, [property], "]-"
label        = ":", identifier
type         = label
property     = "{", {identifier, ":", literal | param}, "}"
param        = "{", identifier, "}"
literal      = string | number
----

=== Interaction with existing features

This proposal drops some functionality around how we handle creating
nodes and relationships:

 - `CREATE (a {param})` where `{param}` is either a map defining many properties
 to be set on the node or a list of maps where one node is created for each item
 of the list. We propose to remove both of these usages.

 - `CREATE (a)-[:T {param}]->(b)` where `{param}` is a map defining all properties
 to be set on the relationship.

 - `CREATE (a:L {prop: 42})-[:R]->(b:B)` where both nodes and relationships are created
 from the same pattern. With this proposal one would have to be more specific and write
 `CREATE (a:L {prop:42}), (b:B), (a)-[:R]->(b)`.

The rationale behind removing the use of parameter maps is to make `CREATE` behave
symmetrical to its non-mutating sibling `MATCH`. Furthermore, if we want to plan
for specific indexing write-operations, we need the information about the property
keys at the time of planning.

The implicit creation of nodes when specifying a relationship pattern is
causing more complexity than whatever benefit it provides to the user. We
believe that forcing the user to be specific about what to create will benefit
both users and implementors of Cypher.

=== Alternatives
The main alternative is to leave the functionality the way it is in Neo4j
versions prior to 3.0. We could also see alternatives where we don't remove all
of the above features but only a subset of them.

== What others do

- SQL has `CREATE TABLE` for creating tables and `INSERT` for creating new
records in a table.
- MongoDB has `create: <collection_name>` for creating documents.
- In SPARQL, you use `INSERT DATA` to add triples.

== Benefits to this proposal

Since `CREATE` already exists in the language, this CIP doesn't introduce any new features, but instead
sends `CREATE` through this formal process, enabling us to clearly specify the behavior we want it to have.
A formal document such as this one could be of good value for a future language specification effort. The ideas we
present to constrain the `CREATE` syntax could also become valuable changes to the language in aligning `CREATE`
more symmetrically to `MATCH`.

== Caveats to this proposal

Not all syntax changes will have time to become deprecated in Cypher 2.3.0, but will have to be deprecated in a 2.3.x release.
This may or may not cause disturbance for users.
