= CIP2017-03-29 Scalar Subqueries and List Subqueries
:numbered:
:toc:
:toc-placement: macro
:source-highlighter: codemirror

*Author:* Tobias Lindaaker <tobias.lindaaker@neotechnology.com>

toc::[]

== Scalar Subqueries and List Subqueries

Scalar Subqueries are read-only subqueries that produce a single value in a single row.
The result of a Scalar Subquery is the single value (in the single row) produced by the subquery.

List Subqueries are read-only subqueries that produce a single value per row, and zero or more rows.
The result of a List Subquery is the list formed by collecting all of the values of all rows produced by the subquery.

=== Syntax

[source, ebnf]
----
Atom = ... | ListSubquery | ScalarSubquery ;

ListSubquery = '[', SingleValueSubquery, ']' ;

ScalarSubquery = 'SCALAR', '(', SingleValueSubquery, ')' ;

SingleValueSubquery = SingleValuePatternQuery
                    | SingleValueUnwindQuery
                    | SingleValueCallQuery
                    | SingleValueQuery
                    ;

SingleValuePatternQuery = PatternPart, [Where], SingleValueReturn ;
SingleValueUnwindQuery  = 'UNWIND', Expression,
                          ['AS', Variable, [Where], Filter] ;
SingleValueCallQuery    = 'CALL', ExplicitProcedureInvocation,
                          'YIELD', YieldItem, [Where], Filter ;
SingleValueQuery  = {{Match | Unwind | Call}-, {With}}-, SingleValueReturn ;
SingleValueReturn = 'RETURN', (Expression | ProjectedMap | Aggregation), Filter ;

Filter = [Order], [Skip], [Limit] ;
----

=== Scalar Subqueries

=== List Subqueries

=== Examples

[source, cypher]
.Filter the contents of an existing list
----
...
RETURN [
    UNWIND existing_list_of_items AS item
    WHERE item.size < 15
    RETURN item
] AS small_items
----

[source, cypher]
.Sort an existing list
----
...
RETURN [
    UNWIND existing_list_of_items AS item
    RETURN item
    ORDER BY item.price
] AS small_items
----

[source, cypher]
.Collect separate lists of friends and enemies
----
MATCH (me:Person {name: $my_name})
RETURN me.name, [
    MATCH (me)-[:FRIEND]-(friend)
    RETURN friend.name
] AS friends, [
    MATCH (me)-[:ENEMY]-(enemy)
    RETURN enemy.name
] AS enemies
----

[source, cypher]
.Unpack the value of a singleton list (or fail if the list is not a singleton)
----
...
RETURN SCALAR (UNWIND list_with_single_item) AS the_item
----

[source, cypher]
.Unpack the single element matching a predicate from a list
----
...
RETURN SCALAR (
    UNWIND existing_list_of_items AS item
    WHERE item.name = "Cabbage"
    // RETURN is not needed from an UNWIND subquery
) AS the_item
----

[source, cypher]
.Unpack the _first_ element matching a predicate from a list
----
...
RETURN SCALAR (
    UNWIND existing_list_of_items AS item
    WHERE item.name CONTAINS "Sweet"
    // RETURN is not needed from an UNWIND subquery
    LIMIT 1
) AS first_item
----

[source, cypher]
.Compute an aggregation of all items in a list
----
...
RETURN SCALAR (
    UNWIND existing_list_of_items AS item
    RETURN avg(item.price)
) AS avg_item_price
----

[source, cypher]
.Compute an aggregation over a sub-pattern
----
MATCH (who:Employee)
RETURN who.name, SCALAR (
    MATCH (who)-[filing:FILED]->(receipt)
    WHERE date.truncate('month', date() - duration('P1M'))
          <= filing.date <
          date.truncate('month', date() - duration('P1M'))
    RETURN sum(receipt.amount)
) AS total_expenses
----


[source, cypher]
.Something
----
RETURN [
    CALL my.cool.Procedure() YIELD theValue
    WHERE theValue.temperatureC < 4.0
    // Return is not needed for CALL subquery with only a single YIELD field
] AS all_cool_values
----
