= Property Graph Model
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Cypher is a graph query language, but it doesn't operate on any arbitrary definition of graph; it operates on a Property Graph.
In a Property Graph, the following elements exist:

- Node
- Relationship
- Path
- Label
- Relationship type
- Property

==== Node

- A _node_ is the basic entity of the graph, with the unique attribute of being able to exist in and of itself.
- A node may have zero or more unique labels.
- A node may have zero or more unique properties.
- Each node contains a unique, comparable id, which defines whether a pair of node references are equal or not.
- A node may have zero or more outgoing relationships.
- A node may have zero or more incoming relationships.

==== Relationship

- A _relationship_ is a directed connection between exactly two nodes, the _start node_ and the _end node_.
- A relationship's direction is said to be _outgoing_ from the start node, and _incoming_ to the end node.
- A relationship has exactly one relationship type.
- A relationship may have zero or more unique properties.
- Each relationship contains a unique, comparable id, which defines whether a pair of relationship references are equal or not.

==== Path

- A _path_ is an odd-sized list of alternating nodes and relationships.
- A path always starts and ends at a node.
- The smallest possible path contains a single node, and is called an _empty_ path.
- A path has a _length_, which is an integer greater than or equal to zero, which is equal to the number of relationships in the path.
- Equality of paths is detailed in the link:../cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence{outfilesuffix}#322-comparability[Comparability CIP].

==== Label

- A _label_ is a nonempty string of Unicode characters that is assigned to one or more nodes.

==== Relationship type

- A _relationship type_ is a nonempty string of Unicode characters that is assigned to one or more relationships.

==== Property

- A _property_ is a pair consisting of a _property key_ and a _property value_.
- A property key is a nonempty string of Unicode characters.
- A property value is an instantiation of one of Cypher's concrete, scalar types, or a list of a concrete, scalar type.
  See the link:../cip/1.accepted/CIP2015-09-16-public-type-system-type-annotation{outfilesuffix}#types-and-type-literal-syntax[type system CIP] for reference.
- A property is uniquely identified by its property key.

=== Graph attributes

- The _size_ of the graph is an integer greater than or equal to zero, and is equal to the number of nodes in the graph.
